# Generated by Django 5.2.7 on 2025-10-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_productrating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='update',
            new_name='updated',
        ),
    ]
